#!/usr/bin/env python3
"""Generate and guard every dual-harness (Claude Code + Codex) derived artifact.

Single source of truth: scripts/dual-harness.json. From it this tool produces
three kinds of generated artifact and, in --check mode, fails if any has drifted:

  1. Vendored skill copies  — a skill authored once (its owner plugin) copied
     byte-for-byte into every plugin that ships it. Required because neither
     harness can reference a skill outside a plugin's own directory (Claude
     sparse-clones one plugin dir; Codex has no plugin-to-plugin dependencies).
  2. Codex plugin manifests — plugins/<name>/.codex-plugin/plugin.json, mirrored
     from the plugin's .claude-plugin/plugin.json plus "skills": "./skills/".
  3. The vendoring state file — scripts/dual-harness-state.json, recording which
     source produced each generated copy and the digest of what was written. It
     lets write mode safely remove a copy after its config edge is deleted,
     while refusing to delete a copy that has local content.

It also validates that every plugin under plugins/ is classified as either
dual-harness or Claude-only, so adding a plugin forces an explicit decision.

The marketplace catalogs (Claude and Codex) live in the marketplace repo, not
here — they're maintained by the cypherpoet-marketplace-kit publish flow.

Usage:
    python3 scripts/sync_dual_harness.py           # write mode (default): (re)generate
    python3 scripts/sync_dual_harness.py --check   # exit 1 on any drift or misclassification

Never hand-edit a generated artifact; edit the source (skill or Claude manifest)
and re-run the bare command to regenerate.
"""

from __future__ import annotations

import argparse
import fnmatch
import hashlib
import json
import shutil
import subprocess
import sys
from pathlib import Path

# Dev/eval material that lives only with a source skill and is never vendored.
IGNORE_DIR_NAMES = {"__pycache__", "evals", ".git"}
IGNORE_DIR_GLOBS = ("*-workspace",)
IGNORE_FILE_NAMES = {".DS_Store"}
IGNORE_FILE_GLOBS = ("*.pyc",)
# OS droppings that never count as local content when deciding whether a
# retired copy is safe to remove.
OS_JUNK_NAMES = {".DS_Store", "Thumbs.db", "Desktop.ini"}
OS_JUNK_GLOBS = ("._*",)
STATE_FILE = Path("scripts") / "dual-harness-state.json"
STATE_COMMENT = (
    "Generated by scripts/sync_dual_harness.py — never hand-edit. Records the "
    "content digest of every generated vendored copy so a retired copy can be "
    "removed safely (a copy with local content is refused; delete its entry "
    "here to adopt it as authored)."
)

# Manifest fields copied verbatim from .claude-plugin into .codex-plugin, in order.
CODEX_MANIFEST_CARRY = ("author", "homepage", "repository", "license", "keywords")


def _dir_ignored(name: str) -> bool:
    return name in IGNORE_DIR_NAMES or any(fnmatch.fnmatch(name, g) for g in IGNORE_DIR_GLOBS)


def _file_ignored(name: str) -> bool:
    return name in IGNORE_FILE_NAMES or any(fnmatch.fnmatch(name, g) for g in IGNORE_FILE_GLOBS)


def _git_visible_files(base: Path) -> set[str] | None:
    """Relative posix paths git would see under base (tracked + untracked minus
    gitignored), or None when base is not inside a git work tree.

    Scoping reads to git's view keeps machine-local gitignored files (*.log,
    .env, editor droppings) out of vendored copies and out of the recorded
    digests — otherwise one machine's junk becomes another machine's phantom
    drift."""
    try:
        proc = subprocess.run(
            ["git", "-C", str(base), "ls-files", "-z", "--cached", "--others", "--exclude-standard"],
            capture_output=True,
            check=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return None
    return {p for p in proc.stdout.decode("utf-8", "surrogateescape").split("\0") if p}


def read_tree(base: Path) -> dict[str, bytes]:
    """Return {relative_posix_path: file_bytes} for base, applying the ignore
    sets and (inside a git work tree) git's tracked/ignored view."""
    out: dict[str, bytes] = {}
    if not base.exists():
        return out
    visible = _git_visible_files(base)
    for path in sorted(base.rglob("*")):
        rel = path.relative_to(base)
        if any(_dir_ignored(part) for part in rel.parts[:-1]):
            continue
        if path.is_dir():
            continue
        if _file_ignored(path.name):
            continue
        if visible is not None and rel.as_posix() not in visible:
            continue
        if not path.is_file():
            continue
        out[rel.as_posix()] = path.read_bytes()
    return out


def read_tree_full(base: Path) -> dict[str, bytes]:
    """Every file under base except OS junk — the view used to prove a retired
    copy has no local content before it is removed. Deliberately wider than
    read_tree: evals/, workspaces, and bytecode count as local content here."""
    out: dict[str, bytes] = {}
    if not base.exists():
        return out
    for path in sorted(base.rglob("*")):
        if path.is_dir():
            continue
        name = path.name
        if name in OS_JUNK_NAMES or any(fnmatch.fnmatch(name, g) for g in OS_JUNK_GLOBS):
            continue
        if not path.is_file():
            continue
        out[path.relative_to(base).as_posix()] = path.read_bytes()
    return out


def write_tree(files: dict[str, bytes], dst: Path) -> None:
    """Replace dst with the given tree."""
    if dst.exists():
        shutil.rmtree(dst)
    for rel, data in files.items():
        target = dst / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(data)


def tree_digest(files: dict[str, bytes]) -> str:
    """Stable digest of a tree, including paths and boundaries."""
    digest = hashlib.sha256()
    for relative_path, data in sorted(files.items()):
        path_bytes = relative_path.encode("utf-8")
        digest.update(len(path_bytes).to_bytes(8, "big"))
        digest.update(path_bytes)
        digest.update(len(data).to_bytes(8, "big"))
        digest.update(data)
    return digest.hexdigest()


def valid_skill_path(value: str) -> bool:
    path = Path(value)
    if path.is_absolute() or ".." in path.parts or path.as_posix() != value:
        return False
    parts = path.parts
    return (
        len(parts) == 4 and parts[0] == "plugins" and parts[2] == "skills"
    ) or (
        len(parts) == 3 and parts[0] in {".agents", ".claude"} and parts[1] == "skills"
    )


def desired_vendor_targets(cfg: dict) -> tuple[dict[str, str], list[str]]:
    desired: dict[str, str] = {}
    problems: list[str] = []
    for edge in cfg["vendored_skills"]:
        source = edge.get("source")
        targets = edge.get("targets")
        if not isinstance(source, str) or not valid_skill_path(source):
            problems.append(f"[vendor] invalid source path: {source!r}")
            continue
        if not isinstance(targets, list) or not targets:
            problems.append(f"[vendor] {source}: targets must be a non-empty array")
            continue
        for target in targets:
            if not isinstance(target, str) or not valid_skill_path(target):
                problems.append(f"[vendor] invalid target path: {target!r}")
                continue
            if target == source:
                problems.append(f"[vendor] source and target are identical: {target}")
                continue
            previous = desired.get(target)
            if previous is not None:
                problems.append(f"[vendor] duplicate target {target}: declared by {previous} and {source}")
                continue
            desired[target] = source
    for source in sorted(set(desired.values()) & set(desired)):
        problems.append(f"[vendor] vendoring chains are not allowed: source is also a target: {source}")
    return desired, problems


def load_vendor_state(root: Path) -> tuple[dict[str, dict], list[str]]:
    """Return {target: {source, tree_sha256}} from the state file and any
    (fatal, non-destructive) shape problems."""
    path = root / STATE_FILE
    if not path.exists():
        return {}, []
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError) as error:
        return {}, [f"[vendor] malformed state file {STATE_FILE.as_posix()}: {error}"]
    entries = data.get("vendored") if isinstance(data, dict) else None
    if not isinstance(entries, dict):
        return {}, [f"[vendor] malformed state file {STATE_FILE.as_posix()}: expected a 'vendored' object"]
    state: dict[str, dict] = {}
    problems: list[str] = []
    for target, entry in entries.items():
        if (
            not valid_skill_path(target)
            or not isinstance(entry, dict)
            or not all(isinstance(entry.get(key), str) and entry.get(key) for key in ("source", "tree_sha256"))
        ):
            problems.append(f"[vendor] malformed state entry for {target!r} in {STATE_FILE.as_posix()}")
            continue
        state[target] = {"source": entry["source"], "tree_sha256": entry["tree_sha256"]}
    return state, problems


def render_vendor_state(state: dict[str, dict]) -> bytes:
    payload = {
        "_comment": STATE_COMMENT,
        "vendored": {target: state[target] for target in sorted(state)},
    }
    return dumps(payload).encode("utf-8")


def build_codex_manifest(claude: dict) -> dict:
    manifest = {
        "name": claude["name"],
        "version": claude["version"],
        "description": claude["description"],
    }
    for key in CODEX_MANIFEST_CARRY:
        if key in claude:
            manifest[key] = claude[key]
    manifest["skills"] = "./skills/"
    return manifest


def dumps(obj: dict) -> str:
    return json.dumps(obj, indent=2, ensure_ascii=False) + "\n"


def load_config(root: Path) -> dict:
    return json.loads((root / "scripts" / "dual-harness.json").read_text(encoding="utf-8"))


def sync(root: Path, write: bool) -> list[str]:
    """Perform (write) or verify (check) every derived artifact. Returns drift/error messages."""
    cfg = load_config(root)
    problems: list[str] = []

    # 0. Classification: every plugin must be dual-harness xor Claude-only.
    existing = {p.name for p in (root / "plugins").iterdir() if p.is_dir()}
    dual = set(cfg["dual_harness_plugins"])
    claude_only = set(cfg["claude_only_plugins"])
    for name in sorted(dual & claude_only):
        problems.append(f"[config] {name} is listed as both dual-harness and Claude-only")
    for name in sorted((dual | claude_only) - existing):
        problems.append(f"[config] {name} is classified but no plugins/{name}/ exists")
    for name in sorted(existing - dual - claude_only):
        problems.append(f"[config] plugins/{name}/ is unclassified — add it to dual_harness_plugins or claude_only_plugins")

    # 1. Vendored skills and the state file that records their digests.
    desired_targets, vendor_config_problems = desired_vendor_targets(cfg)
    problems.extend(vendor_config_problems)
    state, state_problems = load_vendor_state(root)
    problems.extend(state_problems)

    if not vendor_config_problems and not state_problems:
        next_state: dict[str, dict] = {}

        # 1a. Retired edges: remove copies proven untouched; keep everything else.
        for target in sorted(set(state) - set(desired_targets)):
            entry = state[target]
            dst = root / target
            if not write:
                remains = "copy and state entry remain" if dst.exists() or dst.is_symlink() else "state entry remains"
                problems.append(f"[vendor] stale generated copy: {target} ({remains}; was vendored from {entry['source']})")
                continue
            if dst.exists() or dst.is_symlink():
                if dst.is_symlink() or not dst.is_dir() or tree_digest(read_tree_full(dst)) != entry["tree_sha256"]:
                    problems.append(f"[vendor] stale target has local content; refusing to remove: {target} (delete its entry in {STATE_FILE.as_posix()} to adopt it as authored)")
                    next_state[target] = entry
                    continue
                shutil.rmtree(dst)

        # 1b. Configured edges: generate copies and record their digests.
        source_trees: dict[str, dict[str, bytes]] = {}
        for target, source in sorted(desired_targets.items()):
            src = root / source
            if not src.exists():
                problems.append(f"[vendor] source missing: {source}")
                continue
            if source not in source_trees:
                source_trees[source] = read_tree(src)
            src_tree = source_trees[source]
            if not src_tree:
                problems.append(f"[vendor] source has no vendorable files: {source}")
                continue
            dst = root / target
            entry = {"source": source, "tree_sha256": tree_digest(src_tree)}
            if write:
                write_tree(src_tree, dst)
                next_state[target] = entry
            else:
                if read_tree(dst) != src_tree:
                    problems.append(f"[vendor] out of sync: {target} != {source} (run: python3 scripts/sync_dual_harness.py)")
                if state.get(target) != entry:
                    problems.append(f"[vendor] state file out of sync for {target} (run: python3 scripts/sync_dual_harness.py)")
                next_state[target] = entry

        # 1c. The state file itself.
        state_path = root / STATE_FILE
        if write:
            if next_state:
                state_path.parent.mkdir(parents=True, exist_ok=True)
                state_path.write_bytes(render_vendor_state(next_state))
            elif state_path.exists():
                state_path.unlink()
        else:
            stale_only = {t: state[t] for t in set(state) - set(desired_targets)}
            expected = render_vendor_state({**next_state, **stale_only}) if (next_state or stale_only) else None
            on_disk = state_path.read_bytes() if state_path.exists() else None
            if expected != on_disk and not any(p.startswith("[vendor]") for p in problems):
                # Catch-all for hand-edits to the state file (reordering, comment
                # tampering) when every per-target entry above already matched.
                problems.append(f"[vendor] state file out of sync: {STATE_FILE.as_posix()} (run: python3 scripts/sync_dual_harness.py)")

    # 2. Codex manifests.
    for name in sorted(dual):
        if "category" not in cfg["dual_harness_plugins"][name]:
            problems.append(f"[config] {name}: dual_harness_plugins entry needs a 'category'")
        claude_path = root / "plugins" / name / ".claude-plugin" / "plugin.json"
        if not claude_path.exists():
            problems.append(f"[codex-manifest] missing Claude manifest for {name}")
            continue
        claude = json.loads(claude_path.read_text(encoding="utf-8"))
        missing = [k for k in ("name", "version", "description") if k not in claude]
        if missing:
            problems.append(f"[codex-manifest] {name}: Claude manifest missing {', '.join(missing)}")
            continue
        plugin_dir = root / "plugins" / name
        unported = [k for k in ("mcpServers", "hooks", "agents", "commands") if k in claude]
        skills_val = claude.get("skills", "./skills/")
        if not (isinstance(skills_val, str) and skills_val.lstrip("./").rstrip("/") == "skills"):
            unported.append("skills (custom path)")
        for comp in ("commands", "agents", "hooks"):
            if (plugin_dir / comp).is_dir() and comp not in unported:
                unported.append(f"{comp}/ (auto-discovered)")
        if (plugin_dir / ".mcp.json").is_file() and "mcpServers" not in unported:
            unported.append(".mcp.json")
        if unported:
            problems.append(f"[codex-manifest] {name}: Claude-only components ({', '.join(unported)}) — the generator does not carry these into .codex-plugin; port them or make the plugin Claude-only")
            continue
        want = dumps(build_codex_manifest(claude)).encode("utf-8")
        codex_path = plugin_dir / ".codex-plugin" / "plugin.json"
        if write:
            codex_path.parent.mkdir(parents=True, exist_ok=True)
            codex_path.write_bytes(want)
        elif not codex_path.exists() or codex_path.read_bytes() != want:
            problems.append(f"[codex-manifest] out of sync: {codex_path.relative_to(root)} (run: python3 scripts/sync_dual_harness.py)")

    # 3. A Claude-only plugin must not present itself as a Codex plugin.
    for name in sorted(claude_only & existing):
        stale = root / "plugins" / name / ".codex-plugin"
        if stale.exists():
            if write:
                shutil.rmtree(stale)
            else:
                problems.append(f"[codex-manifest] stale .codex-plugin/ for Claude-only plugin {name} (run: python3 scripts/sync_dual_harness.py)")

    return problems


def find_root(start: Path) -> Path:
    for candidate in (start, *start.parents):
        if (candidate / "plugins").is_dir() and (candidate / "scripts" / "dual-harness.json").is_file():
            return candidate
    raise SystemExit("could not locate repo root (needs plugins/ and scripts/dual-harness.json)")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify only; exit 1 on drift")
    args = parser.parse_args()

    root = find_root(Path(__file__).resolve().parent)
    problems = sync(root, write=not args.check)

    if problems:
        for msg in problems:
            print(msg, file=sys.stderr)
        if args.check:
            print(f"\n{len(problems)} dual-harness issue(s). Run: python3 scripts/sync_dual_harness.py", file=sys.stderr)
            return 1
        # In write mode, anything that blocked or skipped generation is still fatal.
        fatal = [p for p in problems if p.startswith(("[config]", "[vendor]")) or "missing Claude manifest" in p or "Claude manifest missing" in p or "Claude-only components" in p]
        if fatal:
            return 1
    print("dual-harness: checked" if args.check else "dual-harness: written", "(no issues)" if not problems else "")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
